name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn checkTs
      - run: yarn eslint
      - if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          REACT_APP_BACKEND_URL: 'https://hujnf3dehe.execute-api.eu-central-1.amazonaws.com'
          REACT_APP_IMAGEKIT_URL: 'https://ik.imagekit.io/hyperremix/handballanalyzer'
          S3_UPLOAD_FILENAME: 'd3v0e30ub418i3-prod'
          SKIP_PREFLIGHT_CHECK: true
        run: |
          yarn build
          cd build && zip ${S3_UPLOAD_FILENAME}.zip -r . && cd ..
          yarn deploy
